//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crazyTattoosEntities : DbContext
    {
        public crazyTattoosEntities()
            : base("name=crazyTattoosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoryInfo> categoryInfoes { get; set; }
        public DbSet<ImageInfo> ImageInfoes { get; set; }
        public DbSet<ImageSlider> ImageSliders { get; set; }
        public DbSet<loginInfo> loginInfoes { get; set; }
        public DbSet<Testimonial> Testimonials { get; set; }
    }
}
